 # Seal with:
 # kubectl create secret generic db-secrets \
 #   --from-literal=MONGODB_PASSWORD=<value> \
 #   --from-literal=POSTGRES_PASSWORD=<value> \
 #   --from-literal=REDIS_PASSWORD=<value> \
 #   --from-literal=MINIO_ACCESS_KEY=<value> \
 #   --from-literal=MINIO_SECRET_KEY=<value> \
 #   --dry-run=client -o yaml | kubeseal \
 #   --controller-name sealed-secrets-controller \
 #   --controller-namespace kube-system \
 #   --format yaml > infra/k8s/security/sealed-secret-db.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secrets
spec:
  template:
    metadata:
      name: db-secrets
    type: Opaque
  encryptedData: {}