FROM apache/airflow:2.7.0

USER airflow

COPY infra/docker/requirements-airflow.txt /opt/airflow/
RUN pip install --no-cache-dir -r /opt/airflow/requirements-airflow.txt

COPY dags/ /opt/airflow/dags/
COPY src/ /opt/airflow/src/

USER root
RUN chown -R airflow: /opt/airflow/dags /opt/airflow/src
USER airflow
