apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smart-travel-api-ingress
spec:
  podSelector:
    matchLabels:
      app: smart-travel-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - podSelector:
            matchLabels:
              app: smart-travel-frontend
      ports:
        - protocol: TCP
          port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smart-travel-frontend-ingress
spec:
  podSelector:
    matchLabels:
      app: smart-travel-frontend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000