apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/api-deployment.yaml
  - ../base/frontend-deployment.yaml
  - ../base/api-hpa.yaml
  - ../base/ingress.yaml
  - ../base/networkpolicy.yaml
  - ../base/pdb.yaml
  - ../security

patchesStrategicMerge:
  - api-prod-patch.yaml
  # - frontend-prod-patch.yaml (create if needed)

images:
  - name: myorg/smart-travel-backend
    newTag: v1.0.0
  - name: myorg/smart-travel-frontend
    newTag: v1.0.0
