apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-secrets
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: smart-travel-vault
    kind: ClusterSecretStore
  target:
    name: airflow-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
  data:
    - secretKey: AIRFLOW__CORE__FERNET_KEY
      remoteRef:
        key: smart-travel/airflow
        property: AIRFLOW__CORE__FERNET_KEY
    - secretKey: AIRFLOW__WEBSERVER__SECRET_KEY
      remoteRef:
        key: smart-travel/airflow
        property: AIRFLOW__WEBSERVER__SECRET_KEY
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: smart-travel/database
        property: POSTGRES_PASSWORD