apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-secret-store.yaml
  - external-secret-api.yaml
  - external-secret-airflow.yaml
  - external-secret-db.yaml
  - sealed-secret-api.yaml
  - sealed-secret-db.yaml