# Seal with:
# kubectl create secret generic api-secrets \
#   --from-literal=SECRET_KEY=<value> \
#   --from-literal=JWT_SECRET=<value> \
#   --from-literal=GOOGLE_PLACES_API_KEY=<value> \
#   --dry-run=client -o yaml | kubeseal \
#   --controller-name sealed-secrets-controller \
#   --controller-namespace kube-system \
#   --format yaml > infra/k8s/security/sealed-secret-api.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secrets
spec:
  template:
    metadata:
      name: api-secrets
    type: Opaque
  encryptedData: {}