global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'smart-travel-api'
    static_configs:
      - targets: ['smart-travel-api-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'smart-travel-frontend'
    static_configs:
      - targets: ['smart-travel-frontend-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-webserver:8080']
    scrape_interval: 30s
